apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cosmosdb
spec:
  type: bindings.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    secretKeyRef:
        name: cosmosdb:endpoint
        key:  cosmosdb:endpoint
  - name: masterKey
    secretKeyRef:
        name: cosmosdb:key
        key:  cosmosdb:key
  - name: database
    value: checkinDb
  - name: collection
    value: default
  - name: partitionKey
    value: user_id

auth:
  secretStore: local-secret-store