apiVersion: v1
kind: Service
metadata:
  namespace: apis
  name: spa-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: react-spa
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: react-spa
    labels:
        app: react-spa
spec:
    replicas: 2
    selector:
        matchLabels:
            app: react-spa
    template:
        metadata:
        labels:
            app: react-spa
    spec:
        containers:
        -   name: react-spa
            image: 
            ports:
            -   containerPort: 80
            resources:
                limits:
                    memory: '128Mi'
                    cpu: '200m'
            livenessProbe:
                 httpGet:
                     path: /index.html
                     port: 80
                 initialDelaySeconds: 15
                 timeoutSeconds: 2
                 periodSeconds: 5
                 failureThreshold: 1
            readinessProbe:
                 httpGet:
                     path: /index.html
                     port: 80
                 initialDelaySeconds: 15
                 periodSeconds: 5
                 failureThreshold: 1